name: AdvancedTeleport
description: A plugin which allows players to request a teleport to other players. Type /tphelp to get a list of commands.
authors: [Niestrat99,Thatsmusic99]
version: 2.1
main: io.github.teambanhammer.tbht_main

commands:
  tpr:
    description: Teleports you to a random place.
    permission: tbh.tp.member.tpr
  tpohere:
    description: (ADMIN ONLY COMMAND) Instantly teleports a player to you.
    permission: tbh.tp.admin.tpohere
  tpaall:
    description: (ADMIN ONLY COMMAND) Sends a "TPAHere"-request to every online player.
    permission: tbh.tp.admin.all
  tpoff:
    description: Stops you from receiving teleport requests.
    permission: tbh.tp.member.off
  tpon:
    description: Allows you to receive teleport requests.
    permission: tbh.tp.member.on
  tpcancel:
    description: Cancels a teleport request you've sent.
    permission: tbh.tp.member.cancel
  tpunblock:
    description: Unblocks a player.
    permission: tbh.tp.member.unblock
  tpblock:
    description: Blocks and prevents a player to send a teleport request to you.
    permission: tbh.tp.member.block
  tpano:
    description: Declines a teleport request someone sent you.
    permission: tbh.tp.member.no
  tpayes:
    description: Accepts a teleport request someone sent you.
    permission: tbh.tp.member.yes
  tpo:
    description: (ADMIN ONLY COMMAND) Instantly teleports you to another player.
    permission: tbh.tp.admin.tpo
  tpahere:
    description: Sends the targeted player a teleport requests to where you are.
    permission: tbh.tp.member.here
  tpa:
    description: Sends the targeted player a teleport request to where they are.
    permission: tbh.tp.member.tpa
  tphelp:
    description: Sends you a list of commands.
    permission: tbh.tp.member.help
  tpalist:
    description: Lists your teleport requests.
    permission: tbh.tp.member.list

permissions:
  # Allows all member permissions
  tbh.tp.member.*:
    default: true
    description: Allows access to member-based commands of the plugin.
    children:
    # All of these are "sub-permissions" of tbh.tp.member.*.
      tbh.tp.member.tpr: true
      tbh.tp.member.off: true
      tbh.tp.member.on: true
      tbh.tp.member.cancel: true
      tbh.tp.member.unblock: true
      tbh.tp.member.block: true
      tbh.tp.member.no: true
      tbh.tp.member.yes: true
      tbh.tp.member.here: true
      tbh.tp.member.help: true
      tbh.tp.member.list: true
  tbh.tp.admin.*:
    default: op
    description: Allows access to admin-based commands of the plugin.
    children:
      tbh.tp.admin.tpohere: true
      tbh.tp.admin.all: true
      tbh.tp.admin.tpo: true
      tbh.tp.admin.help: true